### ISSUE TITLE
Constraints not working

### ISSUE THREAD

**Issue by dwil618** [BogdanMihaiciuc/BMView#23]
I have been trying to get this up and running with ThingWorx 9.1 (using BMCoreUIWidgets), but have found that the constraints for widgets inside a View widget don't seem to be working for most widget types (only found constraints worked for Value Display, Image, Button, and Label widgets).

I get the error below in the application log

> ERROR [widget] An error occurred while calling destroy for BMViewWidget, Id = "BMViewWidget-3". [{}]

**Comment by BogdanMihaiciuc** [comment]
Although I can't say for sure without more information, based on the list of widgets where it works I would guess that it's because you also need to set up size constraints for the other widgets. You can set up a constant width/height constraint for a widget by creating a connection to itself (you will only get the options to add a **Width** or **Height** constraint). 

Alternatively, you can use two constraints per dimension to derive the size. For example, it's not required to set a `width` constraint if you have constraints for both the `leading` and `trailing` attributes since the width will be derived from that (similar to setting both the `left` and `right` properties in CSS).

The reason for this is that those five widgets support intrinsic sizes and view can derive their size based on their content. All other widgets need to have explicit sizing set.

**Comment by dwil618** [comment]
You got it in one! Thanks for the explanation - I did suspect I was doing something wrong! Thanks also for all your great TW tools!
